buildscript {
    repositories {
        google()
        mavenCentral() // Replaced jcenter()
    }

    dependencies {
        // Upgraded from 4.1.0 to modern, stable 8.0.2
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral() // Replaced jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
